### ISSUE TITLE
symfony 5 / PHP 8 

### ISSUE THREAD

**Issue by rtyshyk** [OpenConext/Stepup-saml-bundle#112]
Hi,

Are there any plans to support Symfony 5 / PHP 8?

**Comment by thijskh** [comment]
This will surely happen at some point, if you're interested to help it along a pull request would be most welcome.

**Comment by denzity86** [comment]
Waiting for this one too!

**Comment by thijskh** [comment]
Then see my previous comment…

**Comment by MKodde** [comment]
We are currently testing the contribution by @wdttilburg We merged his work into one of our local feature branches. And are going to code review and test that code there. Once we reached a point that is worthy of a new release we will do so.

**Comment by thijskh** [comment]
Fixed in #122
