### ISSUE TITLE
Symfony as IDP

### ISSUE THREAD

**Issue by dpfaffenbauer** [OpenConext/Stepup-saml-bundle#127]
Hey,

I a struggling with using my Symfony Application with my User Provider to be used as IDP and have an external Application authenticate against me. Can you maybe guide me what I need in order for that to work?

Thanks
Dominik

**Comment by thijskh** [comment]
Hi Dominik. We provide this bundle for free as a service to the community. We are however not in a position to provide ready made instructions or custom implementation support, I'm afraid.

**Comment by dpfaffenbauer** [comment]
@thijskh Do you mabye offer some paid support? We are willing to pay you if we can get it up and running.

**Comment by thijskh** [comment]
We do not offer that I'm afraid

**Comment by dpfaffenbauer** [comment]
Cheers for being open and straight about it.
