### ISSUE TITLE
AdactiveSAS/saml2-bridge-bundle

### ISSUE THREAD

**Issue by moroine** [OpenConext/Stepup-saml-bundle#57]
Hi,

First of all I would like to thank you for that bundle ! 

I was looking creating an identity provider and I started with your bundle. At a first place I wanted to make a pull request to improve that bundle.

Unfortunately I made too much changes which led me to believe that such a PR would never be accepted. 

If you're interested about my changes you could take a look at https://github.com/AdactiveSAS/saml2-bridge-bundle. 

I think this refactor is a little bit more flexible and add some support of Single Logout Service. 

The fact is that I'm new with SAML although I read the whole specification. So I'm trying make some noise in order to attract some people interested to help us evolved that project.

Anyway I would be happy to discuss with you about it.

**Comment by thijskh** [comment]
Thanks for the information. I hope people interested will find your link through this issue. Since the current Stepup-saml-bundle is working fine for us, it's not likely that we'll be migrating to your implementation ourselves in the near future.
