### ISSUE TITLE
Multiple identity providers

### ISSUE THREAD

**Issue by ddeboer** [OpenConext/Stepup-saml-bundle#81]
Looking at this bundle’s configuration, it seems it’s not possible to configure multiple identity providers. My use case is that we have an application (service provider) that users should be able to connect to through two different identity providers.

Is this indeed a limitation of the bundle or did I miss something?

**Comment by pmeulen** [comment]
Hi David,

The bundle is/was developed for use by the OpenConext Stepup applications which uses a single remote IdP only. The underlying libraries support multiple IdPs, so you might be able to use multiple remote IdPs by configuring this at runtime.

**Comment by ddeboer** [comment]
Hey Pieter, thanks for the quick reply! 

Using the libraries directly seems to work fine. While adding configuration support for multiple IdPs should not be too much work, feel free to close this issue if you think this doesn’t make sense for this bundle right now.
